### ISSUE TITLE
Can't download latest Yuzu EA versions

### ISSUE THREAD

**Issue by RootManHD** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#11] opened 2022-11-07 21:02 UTC
There's a problem with the Yuzu EA launcher, it can't install newer versions. It seems that the archives are damaged 
![Screenshot_2](https://user-images.githubusercontent.com/117686325/200414695-b470b354-9148-4134-aff0-9b0d194edc38.png)

**Comment by tonytziorvas** [comment] 2022-11-09 07:32
Same Here

**Comment by Creaticx72** [comment] 2022-11-09 17:26
Same problem.

**Comment by HimDek** [comment] 2022-11-10 22:51
Duplicate of #10

**Closed by HimDek** 2022-11-10 22:51 UTC
